### ISSUE TITLE
[CLI] Check the required parameters

### ISSUE THREAD

**Issue by delhomer** [delhomer/kpconv-torch#9]
The CLI defines `kpconv preprocess`, `kpconv train`, `kpconv test`, `kpconv visualize` and `kpconv plotconv`. These commands share parameters, some of them are required for a subset of commands. One should doublecheck the parameter list and if they should be required for each command.

**Comment by AuBousquet** [comment]
`kpconv visualize`, `kpconv plotconv` are given up. They are not used in the context of this project. The original .py files are kept in the sources, but they are not available from the command line interface anymore. 

The documentation has been updated, to present the CLI options, for each command.

With the current version of the python code, it is not possible to avoid having the two options `-f` and `-d` for the `kpconv test` command, since the program uses the `-d` datapath at two lines, [here](https://github.com/delhomer/kpconv-torch/blob/1cc5ba0eb9796a8a59e9c952f0c16e69096d907c/kpconv_torch/test.py#L134) and [there](https://github.com/delhomer/kpconv-torch/blob/1cc5ba0eb9796a8a59e9c952f0c16e69096d907c/kpconv_torch/test.py#L159).

**Comment by AuBousquet** [comment]
https://github.com/delhomer/kpconv-torch/pull/22
